version: "3.8"

services:
  db:
    image: postgres:13.3
    container_name: "postgres-db"
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env

volumes:
  pgdata: